import boto3
import json
from botocore.exceptions import ClientError
import time
import os

def load_items_from_file(filename):
    """Load items from the JSON file generated by AWS CLI scan"""
    try:
        if not os.path.exists(filename):
            print(f"Error: File '{filename}' not found in current directory")
            print(f"Current directory: {os.getcwd()}")
            print("Files in current directory:")
            for file in os.listdir('.'):
                print(f"  - {file}")
            return None
            
        with open(filename, 'r') as file:
            data = json.load(file)
            
        # The AWS CLI scan output has items in data['Items']
        items = data.get('Items', [])
        print(f"Loaded {len(items)} items from {filename}")
        return items
        
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON file: {e}")
        return None
    except Exception as e:
        print(f"Error reading file: {e}")
        return None

def convert_dynamodb_item(item):
    """Convert DynamoDB JSON format to regular Python dict"""
    def convert_value(value):
        if isinstance(value, dict):
            if 'S' in value:  # String
                return value['S']
            elif 'N' in value:  # Number
                return value['N']
            elif 'B' in value:  # Binary
                return value['B']
            elif 'SS' in value:  # String Set
                return value['SS']
            elif 'NS' in value:  # Number Set
                return value['NS']
            elif 'BS' in value:  # Binary Set
                return value['BS']
            elif 'M' in value:  # Map
                return {k: convert_value(v) for k, v in value['M'].items()}
            elif 'L' in value:  # List
                return [convert_value(v) for v in value['L']]
            elif 'NULL' in value:  # Null
                return None
            elif 'BOOL' in value:  # Boolean
                return value['BOOL']
        return value
    
    return {k: convert_value(v) for k, v in item.items()}

def extract_primary_key(item, table_info):
    """Extract the primary key from an item based on table schema"""
    key = {}
    
    # Get key schema from table info
    key_schema = table_info['Table']['KeySchema']
    
    for key_element in key_schema:
        attr_name = key_element['AttributeName']
        if attr_name in item:
            key[attr_name] = item[attr_name]
        else:
            print(f"Warning: Key attribute '{attr_name}' not found in item")
            return None
    
    return key

def get_table_info(table_name, region='eu-west-1'):
    """Get table information including key schema"""
    try:
        dynamodb_client = boto3.client('dynamodb', region_name=region)
        response = dynamodb_client.describe_table(TableName=table_name)
        return response
    except Exception as e:
        print(f"Error getting table info: {e}")
        return None

def update_customer_ids_from_file(filename='items_to_update.json'):
    """Update customer IDs for items loaded from JSON file"""
    
    # Configuration
    table_name = 'Workout-e5fiatrazzfp5nzvtthoff6gfq-prod'
    region = 'eu-west-1'
    old_customer_id = "8a1699a7-5183-4ada-8796-0319e0475431"
    new_customer_id = "34182408-f041-704a-eb7c-8dd0b8466554"
    
    print("DynamoDB Customer ID Update Script (CloudShell Version)")
    print("=" * 60)
    print(f"Table: {table_name}")
    print(f"Region: {region}")
    print(f"Input file: {filename}")
    print(f"Old customer ID: {old_customer_id}")
    print(f"New customer ID: {new_customer_id}")
    print("-" * 60)
    
    # Load items from file
    items_data = load_items_from_file(filename)
    if items_data is None:
        return False
    
    if len(items_data) == 0:
        print("No items found in the file to update.")
        return True
    
    # Get table information to understand key schema
    print("Getting table information...")
    table_info = get_table_info(table_name, region)
    if table_info is None:
        return False
    
    # Print key schema info
    key_schema = table_info['Table']['KeySchema']
    print("Table key schema:")
    for key_element in key_schema:
        print(f"  - {key_element['AttributeName']} ({key_element['KeyType']})")
    
    # Initialize DynamoDB resource
    dynamodb = boto3.resource('dynamodb', region_name=region)
    table = dynamodb.Table(table_name)
    
    updated_count = 0
    error_count = 0
    skipped_count = 0
    
    print(f"\nProcessing {len(items_data)} items...")
    print("-" * 60)
    
    for i, raw_item in enumerate(items_data, 1):
        try:
            # Convert DynamoDB JSON format to regular Python dict
            item = convert_dynamodb_item(raw_item)
            
            # Extract primary key
            primary_key = extract_primary_key(item, table_info)
            if primary_key is None:
                print(f"✗ Item {i}: Could not extract primary key")
                error_count += 1
                continue
            
            # Check if this item actually has the old customer ID
            current_customer_id = item.get('idCustomer')
            if current_customer_id != old_customer_id:
                print(f"⚠ Item {i}: idCustomer is '{current_customer_id}', not '{old_customer_id}' - skipping")
                skipped_count += 1
                continue
            
            print(f"Updating item {i}/{len(items_data)}: {primary_key}")
            
            # Update the item
            response = table.update_item(
                Key=primary_key,
                UpdateExpression="SET idCustomer = :new_id",
                ConditionExpression="idCustomer = :old_id",
                ExpressionAttributeValues={
                    ":new_id": new_customer_id,
                    ":old_id": old_customer_id
                },
                ReturnValues="UPDATED_NEW"
            )
            
            updated_count += 1
            print(f"✓ Successfully updated item {i}: {primary_key}")
            
            # Small delay to avoid throttling
            time.sleep(0.1)
            
        except ClientError as e:
            error_count += 1
            if e.response['Error']['Code'] == 'ConditionalCheckFailedException':
                print(f"⚠ Item {i}: Condition not met (already updated or changed)")
            else:
                print(f"✗ Error updating item {i}: {e}")
        except Exception as e:
            error_count += 1
            print(f"✗ Unexpected error with item {i}: {e}")
    
    print("-" * 60)
    print("Update process completed!")
    print(f"Total items processed: {len(items_data)}")
    print(f"Successfully updated: {updated_count}")
    print(f"Skipped (wrong customer ID): {skipped_count}")
    print(f"Errors: {error_count}")
    
    return error_count == 0

def preview_updates(filename='items_to_update.json'):
    """Preview what items would be updated without making changes"""
    
    print("PREVIEW MODE - No actual updates will be performed")
    print("=" * 60)
    
    # Load items from file
    items_data = load_items_from_file(filename)
    if items_data is None:
        return False
    
    if len(items_data) == 0:
        print("No items found in the file.")
        return True
    
    old_customer_id = "8a1699a7-5183-4ada-8796-0319e0475431"
    
    print(f"Found {len(items_data)} items in file:")
    print("-" * 60)
    
    valid_items = 0
    for i, raw_item in enumerate(items_data, 1):
        try:
            item = convert_dynamodb_item(raw_item)
            current_customer_id = item.get('idCustomer', 'NOT_FOUND')
            
            # Try to identify the item (look for common key fields)
            item_id = item.get('id') or item.get('ID') or item.get('pk') or 'UNKNOWN'
            
            if current_customer_id == old_customer_id:
                print(f"✓ Item {i}: ID={item_id}, idCustomer={current_customer_id} [WILL UPDATE]")
                valid_items += 1
            else:
                print(f"⚠ Item {i}: ID={item_id}, idCustomer={current_customer_id} [SKIP - wrong customer ID]")
                
        except Exception as e:
            print(f"✗ Item {i}: Error processing - {e}")
    
    print("-" * 60)
    print(f"Items that will be updated: {valid_items}")
    print(f"Items that will be skipped: {len(items_data) - valid_items}")
    
    return True

if __name__ == "__main__":
    print("DynamoDB Customer ID Update Script for CloudShell")
    print("=" * 60)
    
    # Check if file exists
    filename = 'items_to_update.json'
    if not os.path.exists(filename):
        print(f"Error: {filename} not found in current directory")
        print(f"Current directory: {os.getcwd()}")
        print("\nMake sure you have generated the file using:")
        print("aws dynamodb scan --table-name Workout-e5fiatrazzfp5nzvtthoff6gfq-prod \\")
        print('  --filter-expression "idCustomer = :oldId" \\')
        print('  --expression-attribute-values \'{"oldId": {"S": "8a1699a7-5183-4ada-8796-0319e0475431"}}\' \\')
        print("  --output json > items_to_update.json")
        exit(1)
    
    # Ask what to do
    print("What would you like to do?")
    print("1. Preview items that would be updated (recommended first)")
    print("2. Perform the actual update")
    
    choice = input("Enter your choice (1 or 2): ").strip()
    
    if choice == '1':
        preview_updates(filename)
    elif choice == '2':
        # Final confirmation
        confirmation = input("\nAre you sure you want to proceed with the update? (yes/no): ")
        if confirmation.lower() == 'yes':
            success = update_customer_ids_from_file(filename)
            if success:
                print("\n🎉 Script completed successfully!")
            else:
                print("\n⚠ Script completed with errors. Please check the output above.")
        else:
            print("Update cancelled.")
    else:
        print("Invalid choice. Please run the script again and choose 1 or 2.")
