/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://egrryqwz6vhpxptr6x2yofgz3i.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4xo5fy5qyfdkjmggbzhw2bu6qe",
    "aws_cloud_logic_custom": [
        {
            "name": "Garmin360dsl",
            "endpoint": "https://r4hp85viv4.execute-api.eu-west-1.amazonaws.com/prod",
            "region": "eu-west-1"
        },
        {
            "name": "Strava360dsl",
            "endpoint": "https://8vrven0dda.execute-api.eu-west-1.amazonaws.com/prod",
            "region": "eu-west-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-1:af6b6d68-e8d8-489b-ab67-363d00fe64a9",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_71S8wDMsE",
    "aws_user_pools_web_client_id": "2b43se7aighl9f0sqi25apqg41",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
